CREATE SEQUENCE USR_SEQ AS INTEGER START WITH 10;
CREATE SEQUENCE ACCOUNT_SEQ AS INTEGER START WITH 10;
CREATE SEQUENCE TRANSACTION_SEQ AS INTEGER START WITH 10;
CREATE SEQUENCE DBCR_SEQ AS INTEGER START WITH 10;
CREATE SEQUENCE DBCR_ACC_SEQ AS INTEGER START WITH 10;
CREATE SEQUENCE CATEGORY_SEQ AS INTEGER START WITH 10;


CREATE TABLE APP_USER(USER_ID INTEGER DEFAULT NEXTVAL('USR_SEQ') NOT NULL, USERNAME VARCHAR(20), FULLNAME VARCHAR(50), EMAIL VARCHAR(50), PASSWORD VARCHAR(65), IMG VARCHAR(100));

CREATE TABLE APP_ACCOUNT(ACCOUNT_ID INTEGER DEFAULT NEXTVAL('ACCOUNT_SEQ') NOT NULL, NAME VARCHAR(30), BALANCE NUMERIC(10,2),IMG VARCHAR(100), USER_ID INTEGER);

CREATE TABLE APP_CATEGORY(CATEGORY_ID INTEGER DEFAULT NEXTVAL('CATEGORY_SEQ')NOT NULL, NAME VARCHAR(20), IMG VARCHAR(100), USER_ID INTEGER);

CREATE TABLE DEBIT_CREDIT_ACC(ACC_ID INTEGER DEFAULT NEXTVAL('DBCR_ACC_SEQ') NOT NULL, USER_ID INTEGER,ACC_NAME VARCHAR(50), BALANCE NUMERIC(10,2));

CREATE TABLE APP_TRANSACTION(TRANSACTION_ID INTEGER DEFAULT NEXTVAL('TRANSACTION_SEQ') NOT NULL, AMOUNT NUMERIC(10,2), TYPE TINYINT, DATE_COL DATE, ACCOUNT INTEGER, CATEGORY INTEGER, USER_ID INTEGER);

CREATE TABLE DEBIT_CREDIT_TRANSACTION(TRANSACTION_ID INTEGER DEFAULT NEXTVAL('DBCR_SEQ') NOT NULL, AMOUNT NUMERIC(10,2), TYPE TINYINT, DATE_COL DATE, ACCOUNT INTEGER, DEBIT_CREDIT_ACC INTEGER, USER_ID INTEGER);






ALTER TABLE APP_USER
ADD CONSTRAINT USER_TABLE_CONSTRAINTS PRIMARY KEY (USER_ID) ;

ALTER TABLE APP_ACCOUNT ADD CONSTRAINT ACCOUNT_TABLE_PK PRIMARY KEY (ACCOUNT_ID);
ALTER TABLE APP_ACCOUNT ADD CONSTRAINT ACCOUNT_TABLE_FK_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID);

ALTER TABLE APP_CATEGORY ADD CONSTRAINT CATEGORY_TABLE_PK PRIMARY KEY (CATEGORY_ID);
ALTER TABLE APP_CATEGORY ADD CONSTRAINT CATEGORY_TABLE_FK_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ;

ALTER TABLE APP_TRANSACTION ADD CONSTRAINT TRANSACTION_TABLE_PK PRIMARY KEY (TRANSACTION_ID);
ALTER TABLE APP_TRANSACTION ADD CONSTRAINT TRANSACTION_TABLE_FK_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID); 
ALTER TABLE APP_TRANSACTION ADD CONSTRAINT TRANSACTION_TABLE_FK_ACC FOREIGN KEY (ACCOUNT) REFERENCES APP_ACCOUNT(ACCOUNT_ID);
ALTER TABLE APP_TRANSACTION ADD CONSTRAINT TRANSACTION_TABLE_FK_CAT FOREIGN KEY (CATEGORY) REFERENCES APP_CATEGORY(CATEGORY_ID);

ALTER TABLE DEBIT_CREDIT_ACC ADD CONSTRAINT DBCRACC_TABLE_PK PRIMARY KEY (ACC_ID); 
ALTER TABLE DEBIT_CREDIT_ACC ADD CONSTRAINT DBCRACC_TABLE_FK_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ;

ALTER TABLE DEBIT_CREDIT_TRANSACTION ADD CONSTRAINT DBCR_TABLE_PK PRIMARY KEY (TRANSACTION_ID);
ALTER TABLE DEBIT_CREDIT_TRANSACTION ADD CONSTRAINT DBCR_TABLE_FK_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID);
ALTER TABLE DEBIT_CREDIT_TRANSACTION ADD CONSTRAINT DBCR_TABLE_FK_ACC FOREIGN KEY (ACCOUNT) REFERENCES APP_ACCOUNT(ACCOUNT_ID); 
ALTER TABLE DEBIT_CREDIT_TRANSACTION ADD CONSTRAINT DBCR_TABLE_FK_DBACC FOREIGN KEY (DEBIT_CREDIT_ACC) REFERENCES DEBIT_CREDIT_ACC(ACC_ID);


ALTER TABLE DEBIT_CREDIT_ACC ADD CONSTRAINT DBCRACC_UNIQUE_CONSTRAINTS UNIQUE (USER_ID, ACC_NAME) ;

ALTER TABLE APP_ACCOUNT ADD CONSTRAINT ACCOUNT_UNIQUE_CONSTRAINTS UNIQUE (USER_ID, NAME);

ALTER TABLE APP_CATEGORY ADD CONSTRAINT CATEGORY_UNIQUE_CONSTRAINTS UNIQUE (NAME, USER_ID);


